name: 'ã‚«ã‚¹ã‚¿ãƒ ã‚¢ã‚¯ã‚·ãƒ§ãƒ³'
description: 'ã‚¸ãƒ§ãƒ–æƒ…å ±ã‚’å‡¦ç†ã™ã‚‹ã‚«ã‚¹ã‚¿ãƒ ã‚¢ã‚¯ã‚·ãƒ§ãƒ³'
author: 'ã‚µãƒ³ãƒ—ãƒ«ä½œæˆè€…'

# ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å…¥åŠ›ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿
inputs:
  job-name:
    description: 'ã‚¸ãƒ§ãƒ–å'
    required: true
  message:
    description: 'è¡¨ç¤ºã™ã‚‹ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸'
    required: false
    default: 'ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆãƒ¡ãƒƒã‚»ãƒ¼ã‚¸'

# ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å‡ºåŠ›
outputs:
  timestamp:
    description: 'å®Ÿè¡Œæ™‚åˆ»'
    value: ${{ steps.process.outputs.timestamp }}
  status:
    description: 'å‡¦ç†ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹'
    value: ${{ steps.process.outputs.status }}

# ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å®Ÿè¡Œå†…å®¹
runs:
  using: 'composite'
  steps:
    - name: 'ã‚«ã‚¹ã‚¿ãƒ å‡¦ç†å®Ÿè¡Œ'
      id: process
      shell: bash
      run: |
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "ðŸš€ ã‚«ã‚¹ã‚¿ãƒ ã‚¢ã‚¯ã‚·ãƒ§ãƒ³å®Ÿè¡Œä¸­..."
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo ""
        echo "ã‚¸ãƒ§ãƒ–å: ${{ inputs.job-name }}"
        echo "ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸: ${{ inputs.message }}"
        echo "å®Ÿè¡Œæ™‚åˆ»: $(date)"
        echo ""

        # å‡ºåŠ›ã®è¨­å®š
        echo "timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

        # å‡¦ç†çµæžœãƒ•ã‚¡ã‚¤ãƒ«ã®ä½œæˆ
        mkdir -p output
        cat > output/custom-action-result.txt << EOF
        ã€ã‚«ã‚¹ã‚¿ãƒ ã‚¢ã‚¯ã‚·ãƒ§ãƒ³å®Ÿè¡Œçµæžœã€‘
        ã‚¸ãƒ§ãƒ–å: ${{ inputs.job-name }}
        ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸: ${{ inputs.message }}
        å®Ÿè¡Œæ™‚åˆ»: $(date)
        ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹: âœ“ æ­£å¸¸çµ‚äº†
        EOF

        echo "âœ… ã‚«ã‚¹ã‚¿ãƒ ã‚¢ã‚¯ã‚·ãƒ§ãƒ³å®Œäº†"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"

branding:
  icon: 'activity'
  color: 'blue'

